version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tehran"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 25
    directory: ".docker/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tehran"
